title: Sameiet Kirkeveien 90
description: En enkel hjemmeside for Sameiet Kirkeveien 90 som skal samle info som hyppig blir etterspurt
theme: just-the-docs
logo: assets/images/logo.png

url: https://www.kirkeveien90.no

#aux_links:
  #Template Repository: https://github.com/just-the-docs/just-the-docs-template
  #Kirkeveien: https://kirkeveien90.no

gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Rediger denne siden på GitHub."
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_repository: https://github.com/sameiet-kirkeveien-90/sameiet-kirkeveien-90.github.io
gh_edit_view_mode: "edit"

plugins: 
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

nav_external_links:
  - title: Infopakke for nyinnflyttede
    url: https://docs.google.com/document/d/1ASuMmaPJ4z-UNlcXCb_7i6PJlKj656c2bylQFAN6nng/edit?usp=sharing
    opens_in_new_tab: true 
  - title: Facebookgruppe for Kirkeveien 90
    url: https://www.facebook.com/groups/kirkeveien90/
    opens_in_new_tab: true 
  - title: Husordensregler
    url: https://www.dropbox.com/scl/fi/u312mwlkcjusu8z219tsb/HUSORDENSREGLER-FOR-KIRKEVEIEN-90-godkjent-rsm-te-2024.docx?rlkey=ti9s42u1xqrcttbs1dnlcgdto&st=a05uozan&dl=0
    opens_in_new_tab: true 
  - title: Vedtekter
    url: https://www.dropbox.com/scl/fi/so8pw6avq44tmhu4pg8vi/VEDTEKTER-28.-april-2014.doc?rlkey=4zvgmblv4uue6kxyglsdwkkl6&st=31xyo3vi&dl=0
    opens_in_new_tab: true 
  - title: Tidligere utsendt informasjon til beboere
    url: https://www.dropbox.com/scl/fo/imy36unu5h3jculdlo7c0/AO0L1bzPSh4ebXPCDyvh4e4?rlkey=kb0po3veh7kjs7c35v9wn7hf0&st=nxakm8qu&dl=0
    opens_in_new_tab: true 

